### PR TITLE
Change VEP to Ensembl VEP

### PR DESCRIPTION
**Pull request by andrewyatz**
Hi there. Submitting the PR as the official name for the tool is Ensembl VEP and trademarked. Thank you

### CODE REVIEW

**Comment by andrewyatz** [comment]
Closing as I don't think accepting the CLA is tantamount to the change but would appreciate an AlphaMissense maintainer enacting this

**Comment by Avsecz** [comment]
Thanks for flagging. Will apply that change.

**Comment by Avsecz** [comment]
Done!

**Comment by andrewyatz** [comment]
Thank you 😀

**Pull request closed without merging**
